title: "Mo's Blog"
tagline: "Notes, projects, and updates."
description: "Personal blog and updates."

url: "https://mmoradi97.github.io"
baseurl: ""

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
